name: CI to Docker Hub

on:
push: 



jobs:
build:
runs-on: ubuntu-latest


-name: Checamos el repo
 uses: actions/checkout@v2
 
 
 name: Login docker
 uses: docker/login-action@v1
 with:
     username: ${{secrets.DOCKER_USERNAME}}
     password: ${{secrets.DOCKER_HUB}}
     
     
 -name: configuramos el docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@v2
    
    with:
    context: ./
    file: ./Dockerfile
    push: true
    tags: ${{secrets.DOCKER_USERNAME}}/psweb.latest
    
 -name: Image digest
   run: echo ${{steps.docker_build.outputs.digest}}
